# Generated by Django 2.0 on 2017-12-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disputedtournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(verbose_name='Nº Rondas por combate')),
            ],
            options={
                'verbose_name': 'Torneo Disputado',
                'verbose_name_plural': 'Torneos Disputados',
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('alias', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('force', models.PositiveIntegerField(default=4, verbose_name='Fuerza')),
                ('skill', models.PositiveIntegerField(default=3, verbose_name='Habilidad')),
                ('resistance', models.PositiveIntegerField(default=3, verbose_name='Resistencia')),
            ],
            options={
                'verbose_name': 'Luchador',
                'verbose_name_plural': 'Luchadores',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('start_date', models.DateTimeField(verbose_name='Hora inicio')),
                ('finish_date', models.DateTimeField(verbose_name='Hora final')),
                ('fighter_count', models.IntegerField(verbose_name='Nº Jugadores')),
                ('category', models.IntegerField(choices=[(0, 'Pluma'), (1, 'Tigre'), (2, 'León')], default=0, verbose_name='Categoria')),
                ('fighters', models.ManyToManyField(to='main.Fighter', verbose_name='Luchadores')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.AddField(
            model_name='disputedtournament',
            name='name',
            field=models.ManyToManyField(to='main.Tournament', verbose_name='Torneos'),
        ),
    ]
