# Generated by Django 2.0 on 2017-12-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputedtournament',
            name='name',
        ),
        migrations.AddField(
            model_name='disputedtournament',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Tournament'),
            preserve_default=False,
        ),
    ]
