# Generated by Django 2.0 on 2017-12-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171227_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputedtournament',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Tournament'),
        ),
    ]
