# Generated by Django 2.0 on 2017-12-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171227_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='id',
        ),
        migrations.AddField(
            model_name='disputedtournament',
            name='fighters',
            field=models.ManyToManyField(related_name='tournament', to='main.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fighters',
            field=models.ManyToManyField(to='main.Fighter'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
    ]
