# Generated by Django 2.0 on 2017-12-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171228_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='fighters',
        ),
        migrations.AddField(
            model_name='tournament',
            name='dfighters',
            field=models.ManyToManyField(to='main.Fighter', verbose_name='Luchadores'),
        ),
        migrations.AlterField(
            model_name='disputedtournament',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='main.Tournament'),
        ),
    ]
